---
prompt_file: prompts/eli5_sum_or_ext.json
eval_file: data/alce/eli5_eval_bm25_top100_reranked_oracle.json
shot: 0
ndoc: 5
dataset_name: eli5
tag: extraction
model: TinyLlama/TinyLlama-1.1B-Chat-v0.6
temperature: 1.0
top_p: 0.95
use_shorter: extraction
