---
prompt_file: prompts/eli5_sum_or_ext.json
eval_file: data/alce/eli5_eval_bm25_top100_reranked_oracle.json
shot: 1
ndoc: 5
dataset_name: eli5
tag: extraction
model: meta-llama/Meta-Llama-3-8B-Instruct
temperature: 1.0
top_p: 0.95
use_shorter: extraction
