---
prompt_file: prompts/alce/eli5_sum_or_ext.json
eval_file: data/alce/eli5_eval_bm25_top100_reranked_oracle.json
shot: 0
ndoc: 0
ndoc_in_demo: 0
dataset_name: eli5
tag: oracle
model: meta-llama/Meta-Llama-3-8B-Instruct
temperature: 1.0
top_p: 0.95
use_shorter: summary
