---
multi_news_file: /home/dju/datasets/multi_news
wcep_10_file: /home/dju/datasets/wcep-10
shot: 0
ndoc: 0
ndoc_in_demo: 0
dataset_name: mds
tag: claims-gen
model: meta-llama/Meta-Llama-3.1-8B-Instruct
temperature: 1.0
top_p: 0.95
ampere_gpu: True
